import { assetsImage } from "../constants/assets";

export const dataProduct = [
  {
    id: 1,
    title: "Arduino UNO R3",
    price: 1123000,
    newPrice: 0,
    image: assetsImage.im_arduino,
    category: "Arduino",
    quantity: 5,
  },
  {
    id: 2,
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    id: 3,
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    id: 4,
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    id: 5,
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    id: 6,
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    id: 7,
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    id: 8,
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    id: 9,
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    id: 10,
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    id: 11,
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    id: 12,
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    id: 13,
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    id: 14,
    title: "LED RGB 5mm",
    price: 5000,
    newPrice: 0,
    image: assetsImage.im_den_led,
    quantity: 0,
    category: "Đèn LED, Điều khiển LED",
  },
  {
    id: 15,
    title: "Công tắc 2 chiều",
    price: 25000,
    newPrice: 0,
    image: assetsImage.im_dien,
    quantity: 5,
    category: "Điện dân dụng và Công nghiệp",
  },
  {
    id: 16,
    title: "Tấm pin năng lượng mặt trời 100W",
    price: 1500000,
    newPrice: 0,
    image: assetsImage.im_dien_nlmt,
    quantity: 0,
    category: "Điện năng lượng mặt trời",
  },
  {
    id: 17,
    title: "Đồng hồ vạn năng DT830B",
    price: 150000,
    newPrice: 120000,
    image: assetsImage.im_dong_ho,
    quantity: 5,
    category: "Đồng hồ vạn năng",
  },
  {
    id: 18,
    title: "Máy in 3D Ender 3",
    price: 5000000,
    newPrice: 4500000,
    image: assetsImage.im_may_in,
    quantity: 0,
    category: "Máy in 3D, Công nghệ",
  },
  {
    id: 19,
    title: "Module Relay 4 kênh",
    price: 85000,
    newPrice: 0,
    image: assetsImage.im_module,
    quantity: 0,
    category: "Module, Mạch điện",
  },
  {
    id: 20,
    title: "Mỏ hàn điện tử",
    price: 150000,
    newPrice: 0,
    image: assetsImage.im_han,
    quantity: 52,
    category: "Phụ kiện, Dụng cụ",
  },
  {
    id: 21,
    title: "Robot Arduino Car",
    price: 1200000,
    newPrice: 0,
    image: assetsImage.im_robot,
    quantity: 5,
    category: "Robot, Phụ kiện DIY",
  },
  {
    id: 22,
    title: "Arduino Nano",
    price: 850000,
    newPrice: 0,
    image: assetsImage.im_arduino,
    quantity: 5,
    category: "Arduino",
  },
  {
    id: 23,
    title: "Cảm biến siêu âm HC-SR04",
    price: 35000,
    newPrice: 0,
    image: assetsImage.im_cam_bien,
    quantity: 51,
    category: "Cảm biến",
  },
  {
    id: 24,
    title: "LED Strip RGB 1m",
    price: 150000,
    newPrice: 120000,
    image: assetsImage.im_den_led,
    quantity: 53,
    category: "Đèn LED, Điều khiển LED",
  },
  {
    id: 25,
    title: "Mạch điều khiển LED WS2812",
    price: 250000,
    newPrice: 0,
    image: assetsImage.im_module,
    quantity: 0,
    category: "Module, Mạch điện",
  },
  {
    id: 26,
    title: "Arduino UNO R3",
    price: 1123000,
    newPrice: 0,
    image: assetsImage.im_arduino,
    category: "Arduino",
    quantity: 5,
  },
  {
    id: 27,
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    id: 28,
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    id: 29,
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    id: 30,
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    id: 31,
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    id: 32,
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    id: 33,
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    id: 34,
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    id: 35,
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    id: 36,
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    id: 37,
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    id: 38,
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    id: 39,
    title: "LED RGB 5mm",
    price: 5000,
    newPrice: 0,
    image: assetsImage.im_den_led,
    quantity: 0,
    category: "Đèn LED, Điều khiển LED",
  },
  {
    id: 40,
    title: "Công tắc 2 chiều",
    price: 25000,
    newPrice: 0,
    image: assetsImage.im_dien,
    quantity: 5,
    category: "Điện dân dụng và Công nghiệp",
  },
  {
    id: 41,
    title: "Tấm pin năng lượng mặt trời 100W",
    price: 1500000,
    newPrice: 0,
    image: assetsImage.im_dien_nlmt,
    quantity: 0,
    category: "Điện năng lượng mặt trời",
  },
  {
    id: 42,
    title: "Đồng hồ vạn năng DT830B",
    price: 150000,
    newPrice: 120000,
    image: assetsImage.im_dong_ho,
    quantity: 5,
    category: "Đồng hồ vạn năng",
  },
  {
    id: 43,
    title: "Máy in 3D Ender 3",
    price: 5000000,
    newPrice: 4500000,
    image: assetsImage.im_may_in,
    quantity: 0,
    category: "Máy in 3D, Công nghệ",
  },
  {
    id: 44,
    title: "Module Relay 4 kênh",
    price: 85000,
    newPrice: 0,
    image: assetsImage.im_module,
    quantity: 0,
    category: "Module, Mạch điện",
  },
  {
    id: 45,
    title: "Mỏ hàn điện tử",
    price: 150000,
    newPrice: 0,
    image: assetsImage.im_han,
    quantity: 52,
    category: "Phụ kiện, Dụng cụ",
  },
  {
    id: 46,
    title: "Robot Arduino Car",
    price: 1200000,
    newPrice: 0,
    image: assetsImage.im_robot,
    quantity: 5,
    category: "Robot, Phụ kiện DIY",
  },
  {
    id: 47,
    title: "Arduino Nano",
    price: 850000,
    newPrice: 0,
    image: assetsImage.im_arduino,
    quantity: 5,
    category: "Arduino",
  },
  {
    id: 48,
    title: "Cảm biến siêu âm HC-SR04",
    price: 35000,
    newPrice: 0,
    image: assetsImage.im_cam_bien,
    quantity: 51,
    category: "Cảm biến",
  },
  {
    id: 49,
    title: "LED Strip RGB 1m",
    price: 150000,
    newPrice: 120000,
    image: assetsImage.im_den_led,
    quantity: 53,
    category: "Đèn LED, Điều khiển LED",
  },
  {
    id: 50,
    title: "Mạch điều khiển LED WS2812",
    price: 250000,
    newPrice: 0,
    image: assetsImage.im_module,
    quantity: 0,
    category: "Module, Mạch điện",
  },
];

export const dataProducts = [
  {
    id: 1,
    title: "Động cơ giảm tốc GA12-N20 12V 235 rpm",
    price: 1123000,
    newPrice: 0,
    quantity: 0,
    image: assetsImage.im_dong_co,
  },
  {
    id: 2,
    title: "Động cơ giảm tốc GA12-N20 12V 235 rpm",
    price: 1123000,
    newPrice: 0,
    quantity: 53,
    image: assetsImage.im_dong_co,
  },
  {
    id: 3,
    title: "Động cơ giảm tốc GA12-N20 12V 235 rpm",
    price: 1123000,
    newPrice: 0,
    quantity: 53,
    image: assetsImage.im_dong_co,
  },
  {
    id: 4,
    title: "Động cơ giảm tốc GA12-N20 12V 235 rpm",
    price: 1123000,
    newPrice: 0,
    quantity: 0,
    image: assetsImage.im_dong_co,
  },
  {
    id: 5,
    title:
      "Động cơ giảm tốc GA12-N20 12V 235 rpmsss sssss ssssssssssssssssssssssssssssssss",
    price: 1123000,
    newPrice: 0,
    quantity: 53,
    image: assetsImage.im_dong_co,
  },
  {
    id: 6,
    title: "Động cơ giảm tốc GA12-N20 12V 235 rpm",
    price: 1123000,
    newPrice: 0,
    quantity: 53,
    image: assetsImage.im_dong_co,
  },
];

export const dataBlog = [
  {
    id: 1,
    title:
      "Các Lỗi Thường Gặp Khi Sử Dụng ESP8266 Với Chip Nạp CH340 Và Cách Khắc Phục",
    content:
      "ESP8266 là một module WiFi phổ biến trong các dự án IoT, thường được sử dụng với chip nạp CH340 do tính năng đơn giản và giá thành rẻ. Tuy nhiên, khi kết hợp hai thiết bị này, người dùng đôi khi sẽ gặp phải một số lỗi phổ biến. Dưới đây là một số […]",
    image: assetsImage.im_ui,
    label: "tài liệu hướng dẫn",
    date: "20/02/2023",
  },
  {
    id: 2,
    title:
      "Các Lỗi Thường Gặp Khi Sử Dụng ESP8266 Với Chip Nạp CH340 Và Cách Khắc Phục",
    content:
      "ESP8266 là một module WiFi phổ biến trong các dự án IoT, thường được sử dụng với chip nạp CH340 do tính năng đơn giản và giá thành rẻ. Tuy nhiên, khi kết hợp hai thiết bị này, người dùng đôi khi sẽ gặp phải một số lỗi phổ biến. Dưới đây là một số […]",
    image: assetsImage.im_ui,
    label: "tài liệu hướng dẫn",
    date: "20/02/2023",
  },
  {
    id: 3,
    title:
      "Các Lỗi Thường Gặp Khi Sử Dụng ESP8266 Với Chip Nạp CH340 Và Cách Khắc Phục",
    content:
      "ESP8266 là một module WiFi phổ biến trong các dự án IoT, thường được sử dụng với chip nạp CH340 do tính năng đơn giản và giá thành rẻ. Tuy nhiên, khi kết hợp hai thiết bị này, người dùng đôi khi sẽ gặp phải một số lỗi phổ biến. Dưới đây là một số […]",
    image: assetsImage.im_ui,
    label: "tài liệu hướng dẫn",
    date: "20/02/2023",
  },
  {
    id: 4,
    title:
      "Các Lỗi Thường Gặp Khi Sử Dụng ESP8266 Với Chip Nạp CH340 Và Cách Khắc Phục",
    content:
      "ESP8266 là một module WiFi phổ biến trong các dự án IoT, thường được sử dụng với chip nạp CH340 do tính năng đơn giản và giá thành rẻ. Tuy nhiên, khi kết hợp hai thiết bị này, người dùng đôi khi sẽ gặp phải một số lỗi phổ biến. Dưới đây là một số […]",
    image: assetsImage.im_ui,
    label: "tài liệu hướng dẫn",
    date: "20/02/2023",
  },
  {
    id: 5,
    title:
      "Các Lỗi Thường Gặp Khi Sử Dụng ESP8266 Với Chip Nạp CH340 Và Cách Khắc Phục",
    content:
      "ESP8266 là một module WiFi phổ biến trong các dự án IoT, thường được sử dụng với chip nạp CH340 do tính năng đơn giản và giá thành rẻ. Tuy nhiên, khi kết hợp hai thiết bị này, người dùng đôi khi sẽ gặp phải một số lỗi phổ biến. Dưới đây là một số […]",
    image: assetsImage.im_ui,
    label: "tài liệu hướng dẫn",
    date: "20/02/2023",
  },
  {
    id: 6,
    title:
      "Các Lỗi Thường Gặp Khi Sử Dụng ESP8266 Với Chip Nạp CH340 Và Cách Khắc Phục",
    content:
      "ESP8266 là một module WiFi phổ biến trong các dự án IoT, thường được sử dụng với chip nạp CH340 do tính năng đơn giản và giá thành rẻ. Tuy nhiên, khi kết hợp hai thiết bị này, người dùng đôi khi sẽ gặp phải một số lỗi phổ biến. Dưới đây là một số […]",
    image: assetsImage.im_ui,
    label: "tài liệu hướng dẫn",
    date: "20/02/2023",
  },
];
