import { assetsImage } from "../constants/assets";

export const dataProduct = [
  {
    title: "Arduino UNO R3",
    price: 1123000,
    newPrice: 0,
    image: assetsImage.im_arduino,
    category: "Arduino",
    quantity: 5,
  },
  {
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    title: "LED RGB 5mm",
    price: 5000,
    newPrice: 0,
    image: assetsImage.im_den_led,
    quantity: 0,
    category: "Đèn LED, Điều khiển LED",
  },
  {
    title: "Công tắc 2 chiều",
    price: 25000,
    newPrice: 0,
    image: assetsImage.im_dien,
    quantity: 5,
    category: "Điện dân dụng và Công nghiệp",
  },
  {
    title: "Tấm pin năng lượng mặt trời 100W",
    price: 1500000,
    newPrice: 0,
    image: assetsImage.im_dien_nlmt,
    quantity: 0,
    category: "Điện năng lượng mặt trời",
  },
  {
    title: "Đồng hồ vạn năng DT830B",
    price: 150000,
    newPrice: 120000,
    image: assetsImage.im_dong_ho,
    quantity: 5,
    category: "Đồng hồ vạn năng",
  },
  {
    title: "Máy in 3D Ender 3",
    price: 5000000,
    newPrice: 4500000,
    image: assetsImage.im_may_in,
    quantity: 0,
    category: "Máy in 3D, Công nghệ",
  },
  {
    title: "Module Relay 4 kênh",
    price: 85000,
    newPrice: 0,
    image: assetsImage.im_module,
    quantity: 0,
    category: "Module, Mạch điện",
  },
  {
    title: "Mỏ hàn điện tử",
    price: 150000,
    newPrice: 0,
    image: assetsImage.im_han,
    quantity: 52,
    category: "Phụ kiện, Dụng cụ",
  },
  {
    title: "Robot Arduino Car",
    price: 1200000,
    newPrice: 0,
    image: assetsImage.im_robot,
    quantity: 5,
    category: "Robot, Phụ kiện DIY",
  },
  {
    title: "Arduino Nano",
    price: 850000,
    newPrice: 0,
    image: assetsImage.im_arduino,
    quantity: 5,
    category: "Arduino",
  },
  {
    title: "Cảm biến siêu âm HC-SR04",
    price: 35000,
    newPrice: 0,
    image: assetsImage.im_cam_bien,
    quantity: 51,
    category: "Cảm biến",
  },
  {
    title: "LED Strip RGB 1m",
    price: 150000,
    newPrice: 120000,
    image: assetsImage.im_den_led,
    quantity: 53,
    category: "Đèn LED, Điều khiển LED",
  },
  {
    title: "Mạch điều khiển LED WS2812",
    price: 250000,
    newPrice: 0,
    image: assetsImage.im_module,
    quantity: 0,
    category: "Module, Mạch điện",
  },
  {
    title: "Arduino UNO R3",
    price: 1123000,
    newPrice: 0,
    image: assetsImage.im_arduino,
    category: "Arduino",
    quantity: 5,
  },
  {
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    title: "Cảm biến nhiệt độ DHT11",
    price: 1145000,
    newPrice: 35000,
    image: assetsImage.im_cam_bien,
    quantity: 0,
    category: "Cảm biến",
  },
  {
    title: "Combo Arduino + Cảm biến",
    price: 1500000,
    newPrice: 1200000,
    image: assetsImage.im_combo,
    quantity: 0,
    category: "Combo khuyến mãi",
  },
  {
    title: "LED RGB 5mm",
    price: 5000,
    newPrice: 0,
    image: assetsImage.im_den_led,
    quantity: 0,
    category: "Đèn LED, Điều khiển LED",
  },
  {
    title: "Công tắc 2 chiều",
    price: 25000,
    newPrice: 0,
    image: assetsImage.im_dien,
    quantity: 5,
    category: "Điện dân dụng và Công nghiệp",
  },
  {
    title: "Tấm pin năng lượng mặt trời 100W",
    price: 1500000,
    newPrice: 0,
    image: assetsImage.im_dien_nlmt,
    quantity: 0,
    category: "Điện năng lượng mặt trời",
  },
  {
    title: "Đồng hồ vạn năng DT830B",
    price: 150000,
    newPrice: 120000,
    image: assetsImage.im_dong_ho,
    quantity: 5,
    category: "Đồng hồ vạn năng",
  },
  {
    title: "Máy in 3D Ender 3",
    price: 5000000,
    newPrice: 4500000,
    image: assetsImage.im_may_in,
    quantity: 0,
    category: "Máy in 3D, Công nghệ",
  },
  {
    title: "Module Relay 4 kênh",
    price: 85000,
    newPrice: 0,
    image: assetsImage.im_module,
    quantity: 0,
    category: "Module, Mạch điện",
  },
  {
    title: "Mỏ hàn điện tử",
    price: 150000,
    newPrice: 0,
    image: assetsImage.im_han,
    quantity: 52,
    category: "Phụ kiện, Dụng cụ",
  },
  {
    title: "Robot Arduino Car",
    price: 1200000,
    newPrice: 0,
    image: assetsImage.im_robot,
    quantity: 5,
    category: "Robot, Phụ kiện DIY",
  },
  {
    title: "Arduino Nano",
    price: 850000,
    newPrice: 0,
    image: assetsImage.im_arduino,
    quantity: 5,
    category: "Arduino",
  },
  {
    title: "Cảm biến siêu âm HC-SR04",
    price: 35000,
    newPrice: 0,
    image: assetsImage.im_cam_bien,
    quantity: 51,
    category: "Cảm biến",
  },
  {
    title: "LED Strip RGB 1m",
    price: 150000,
    newPrice: 120000,
    image: assetsImage.im_den_led,
    quantity: 53,
    category: "Đèn LED, Điều khiển LED",
  },
  {
    title: "Mạch điều khiển LED WS2812",
    price: 250000,
    newPrice: 0,
    image: assetsImage.im_module,
    quantity: 0,
    category: "Module, Mạch điện",
  },
];

export const dataProducts = [
  {
    title: "Động cơ giảm tốc GA12-N20 12V 235 rpm",
    price: 1123000,
    newPrice: 0,
    quantity: 0,
    image: assetsImage.im_dong_co,
  },
  {
    title: "Động cơ giảm tốc GA12-N20 12V 235 rpm",
    price: 1123000,
    newPrice: 0,
    quantity: 53,
    image: assetsImage.im_dong_co,
  },
  {
    title: "Động cơ giảm tốc GA12-N20 12V 235 rpm",
    price: 1123000,
    newPrice: 0,
    quantity: 53,
    image: assetsImage.im_dong_co,
  },
  {
    title: "Động cơ giảm tốc GA12-N20 12V 235 rpm",
    price: 1123000,
    newPrice: 0,
    quantity: 0,
    image: assetsImage.im_dong_co,
  },
  {
    title:
      "Động cơ giảm tốc GA12-N20 12V 235 rpmsss sssss ssssssssssssssssssssssssssssssss",
    price: 1123000,
    newPrice: 0,
    quantity: 53,
    image: assetsImage.im_dong_co,
  },
  {
    title: "Động cơ giảm tốc GA12-N20 12V 235 rpm",
    price: 1123000,
    newPrice: 0,
    quantity: 53,
    image: assetsImage.im_dong_co,
  },
];
